apiVersion: v1 # Versi API Kubernetes yang dipakai untuk object Service
kind: Secret # Menandakan bahwa file ini membuat Secret
metadata: # Metadata untuk Secret
  name: mongo-secret # Nama Secret
type: Opaque # Jenis Secret, Opaque berarti data disimpan dalam bentuk key-value biasa
data:
  MONGO_ROOT_USERNAME: YWRtaW4= # Nilai username MongoDB yang sudah di-encode dalam base64 (admin)
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA== # Nilai password MongoDB yang sudah di-encode dalam base64 (supersecretpassword)
