apiVersion: v1 # Versi API kubernetes
kind: Secret # Jenis objek yang akan dibuat adalah Secret
metadata: # Metadata dari Secret yang akan dibuat
  name: rabbitmq-secret # Nama dari Secret yang akan dibuat
  namespace: messaging # Tambahkan namespace agar secret tersedia di namespace yang benar
type: Opaque # Jenis Secret, Opaque berarti data disimpan dalam bentuk key-value biasa
data: # Data yang akan disimpan dalam Secret, harus di-encode dalam base64
  RABBITMQ_DEFAULT_USER: YXBwdXNlcg== # Nilai dari RABBITMQ_DEFAULT_USER yang sudah di-encode dalam base64 (appuser)
  RABBITMQ_DEFAULT_PASS: cGFzc3dvcmQxMjM= # Nilai dari RABBITMQ_DEFAULT_PASS yang sudah di-encode dalam base64 (password123)
