apiVersion: apps/v1 # Versi API Kubernetes untuk Deployment
kind: Deployment # Jenis objek yang akan dibuat adalah Deployment
metadata: # Metadata dari Deployment yang akan dibuat
  name: shipping-service # Nama dari Deployment yang akan dibuat
  namespace: ecommerce # Namespace tempat Deployment akan dibuat
  labels: # Label yang akan diterapkan pada Deployment
    app: shipping-service # Label yang menunjukkan bahwa Deployment ini adalah untuk aplikasi shipping-service
spec: # Spesifikasi dari Deployment
  replicas: 1 # Jumlah replika Pod yang akan dibuat, dalam hal ini hanya 1 untuk pengembangan
  selector: # Selector untuk memilih Pod yang akan dikelola oleh Deployment
    matchLabels: # Label yang harus dimiliki oleh Pod yang akan dikelola oleh Deployment
      app: shipping-service # Label yang menunjukkan bahwa Pod ini adalah untuk aplikasi shipping-service
  template: # Template untuk Pod yang akan dibuat oleh Deployment
    metadata: # Metadata dari Pod yang akan dibuat
      labels: # Label yang akan diterapkan pada Pod yang dibuat
        app: shipping-service # Label yang menunjukkan bahwa Pod ini adalah untuk aplikasi shipping-service
    spec: # Spesifikasi dari Pod yang akan dibuat
      initContainers: # Daftar init container yang akan dijalankan sebelum container utama dijalankan
        - name: wait-for-rabbitmq # Nama init container
          image: busybox:1.36 # Gambar Docker yang akan digunakan untuk init container, menggunakan BusyBox untuk menjalankan perintah sederhana
          command: # Perintah yang akan dijalankan dalam init container untuk menunggu RabbitMQ siap
            - sh # Perintah shell untuk menjalankan perintah berikutnya
            - -c # Opsi untuk menjalankan perintah dalam mode shell
            - until nc -z rabbitmq.ecommerce.svc.cluster.local 5672; do echo waiting for rabbitmq; sleep 2; done # Perintah untuk memeriksa koneksi ke RabbitMQ pada port 5672, jika belum siap akan menunggu dan mencoba lagi setiap 2 detik
      containers: # Daftar container yang akan dijalankan dalam Pod
        - name: shipping-service # Nama container
          image: ghcr.io/erlanggajuni45/shipping-service:latest # Gambar Docker yang akan digunakan untuk container
          imagePullPolicy: IfNotPresent # Kebijakan untuk menarik gambar Docker, IfNotPresent berarti hanya akan menarik gambar jika belum ada di node
          ports: # Daftar port yang akan dibuka oleh container
            - containerPort: 3001 # Port yang akan dibuka oleh container untuk komunikasi dengan aplikasi
          env: # Daftar environment variable yang akan diterapkan pada container
            - name: AMQP_URL # Nama environment variable yang akan digunakan dalam aplikasi untuk mengakses RabbitMQ
              value: 'amqp://appuser:password123@rabbitmq.ecommerce.svc.cluster.local:5672' # Nilai dari environment variable AMQP_URL yang berisi URL koneksi ke RabbitMQ, menggunakan nama layanan dan namespace untuk mengakses RabbitMQ dalam cluster Kubernetes
