apiVersion: v1 # Versi API kubernetes
kind: Service # Jenis objek yang akan dibuat adalah Service
metadata: # Metadata dari Service yang akan dibuat
  name: shipping-service # Nama dari Service yang akan dibuat
  namespace: ecommerce # Namespace tempat Service akan dibuat
spec: # Spesifikasi dari Service
  selector: # Selector untuk memilih Pod yang akan dilayani oleh Service
    app: shipping-service # Label yang harus dimiliki oleh Pod yang akan dilayani oleh Service
  ports: # Daftar port yang akan dibuka oleh Service
    - protocol: TCP # Protokol yang digunakan untuk komunikasi, dalam hal ini TCP
      port: 3001 # Port yang akan dibuka oleh Service untuk komunikasi dengan aplikasi
      targetPort: 3001 # Port yang akan dituju pada Pod untuk komunikasi dengan aplikasi
