apiVersion: v1 # Versi API kubernetes
kind: Namespace # Jenis objek yang akan dibuat adalah Namespace
metadata: # Metadata dari Namespace yang akan dibuat
  name: ecommerce # Nama dari Namespace yang akan dibuat adalah ecommerce
  labels: # Label yang akan diterapkan pada Namespace
    istio-injection: enabled # Label untuk mengaktifkan Istio sidecar injection pada Namespace ini, sehingga semua Pod yang dibuat di dalam Namespace ini akan otomatis memiliki sidecar Istio yang terpasang untuk fitur-fitur seperti observability, traffic management, dan security.
